[project]
name = "llm-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.10.0",
    "datasets>=4.0.0",
    "ipykernel>=6.30.1",
    "tokenizers>=0.21.4",
    "torch>=2.8.0",
]
